version: '3'

networks:
  default:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 8081:8081
    depends_on:
      - "db"
    volumes:
      - ./:/src
      - gomodules:/go/pkg/mod

  db:
    image: postgres
    container_name: oja-postgres
    environment:
      POSTGRES_DB: oja
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

volumes:
  gomodules:
